# Generated by Django 6.0.7 on 2026-07-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("COD", "Cash on Delivery")], default="COD", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Paid", "Paid")],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
