# Generated by Django 6.0.7 on 2026-07-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                default="profiles/default.jpg", upload_to="profiles/"
            ),
        ),
    ]
