# Generated by Django 6.0.7 on 2026-07-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("owner", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="restaurants/")),
                ("location", models.CharField(max_length=200)),
                ("cuisine", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=4.5, max_digits=2),
                ),
                ("opening_time", models.TimeField()),
                ("closing_time", models.TimeField()),
                ("is_open", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
