# Generated by Django 6.0.7 on 2026-07-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("Weight Loss", "Weight Loss"),
                            ("Weight Gain", "Weight Gain"),
                            ("Maintain Weight", "Maintain Weight"),
                        ],
                        max_length=30,
                    ),
                ),
                ("budget", models.DecimalField(decimal_places=2, max_digits=8)),
                ("cuisine", models.CharField(max_length=100)),
                ("recommended_food", models.CharField(max_length=150)),
                ("calories", models.IntegerField()),
                ("protein", models.IntegerField()),
                ("carbs", models.IntegerField()),
                ("fats", models.IntegerField()),
            ],
        ),
    ]
